/* An ordered curriculum with activity-specific tasks, evidence and changed cases. */
'use strict';
const HLTraining=(()=>{
  const VERSION=2;
  const RUBRIC_VERSION=1;
  const reviewCriteria=[
    {key:'conditions',label:'States the changed conditions and what stays constant',anchor:'Names the changed input, controlled inputs and relevant sign convention before comparing.'},
    {key:'prediction',label:'Predicts direction and, where relevant, magnitude',anchor:'Commits a reasoned direction before the reveal; uses the supplied ratios when a magnitude is requested.'},
    {key:'evidence',label:'Chooses and compares relevant model evidence',anchor:'Selects the appropriate model, stations and layer; compares saved outputs with other inputs held constant.'},
    {key:'mechanism',label:'Connects the causal steps and avoids the identified misconception',anchor:'Explains the variable-to-variable chain using the saved evidence, including the distinction named in the activity criterion.'},
    {key:'limits',label:'States an assumption, missing datum or limit of the conclusion',anchor:'Names a relevant model assumption or missing datum and explains which conclusion it prevents.'}
  ];
  const original=Object.fromEntries(HL_LESSONS.map(l=>[l.id,l]));
  const oldMetadata=Object.fromEntries(HL_V2_MODULES.flatMap(m=>(m.activities||[]).map(a=>[a.lessonId,a])));
  const lessons=[];
  const q=(prompt,options,why,revisit,criterion)=>({prompt,options,answer:0,why,revisit,criterion});
  const cmp=(control,label,extra={})=>({kind:'compare',control,label,...extra});
  const select=(options,label,extra={})=>({kind:'selection',options,label,...extra});
  const gate=(keys,label)=>({kind:'gates',keys,label});
  const outcomes=[
    'Construct and interpret a blade element: separate velocity, pitch, angle of attack and force direction.',
    'Predict hover and vertical-flow changes while stating the controlled conditions and model limits.',
    'Explain how local velocity, flapping, cyclic and inflow asymmetry change rotor response.',
    'Interpret power demand and aerodynamic limits without treating a model as aircraft approval.',
    'Explain how a ground pivot or a changed anti-torque balance changes the moment balance.',
    'Connect local driving and braking forces with the rotor energy budget.',
    'Choose relevant evidence and explain a new problem across several aerodynamic mechanisms.'
  ];
  const titles=['Rotor lift & local flow','Hover & vertical flow','Forward flight & rotor response','Power & aerodynamic limits','Constraints & anti-torque','Autorotation & rotor energy','Integrated flight problems'];
  HL_V2_MODULES.forEach((m,i)=>{m.title=titles[i];m.outcome=outcomes[i];m.available=true;m.activities=[];m.spine=[];});
  function add(mi,source,config={}){
    const m=HL_V2_MODULES[mi-1],base=original[source],old=oldMetadata[source]||{};
    const id=config.id||`cbt-${m.id}-${config.key||source}`;
    const a={...old,lessonId:id,legacyLessonId:source,title:base.title,mode:'explore',kicker:'PRACTICE',widget:base.widget,version:VERSION,transfer:false,check:null,...config};
    const guide=HL_LEARNING_GUIDES[id];
    a.summary=a.task;a.modeAction=a.task;a.criteria=a.criterion;a.bodyHtml=guide?.bodyHtml??config.bodyHtml??base.body;a.takeaways=guide?.takeaways??config.takeaways??base.takeaways;
    delete a.completionRoute;delete a.completionLabel;delete a.modeLead;delete a.modeText;delete a.actionLabel;
    lessons.push({...base,id});m.activities.push(a);return a;
  }
  const angleCheck=n=>{const theta=10+n%5,phi=3+n%3,alpha=theta-phi;return q(`With pitch θ = ${theta}° and inflow φ = ${phi}°, what is α in the stated convention?`,[`${alpha}°: pitch minus inflow.`,`${theta+phi}°: pitch plus inflow.`,`${theta}°: angle of attack always equals pitch.`],'α = θ − φ. The chord is measured from the rotor plane; α is measured from the local relative wind.','cbt-m1-bladeelement','angles');};
  const localForce=n=>q(`A normal-flow element has positive lift. Its relative-flow direction rotates ${n%2?'10° toward':'5° away from'} the rotor plane while geometric pitch stays fixed. Which direction defines the new lift vector?`,['Normal to the new local relative airflow.','Along the unchanged blade chord.','Along the blade span.'],'Lift is normal to relative airflow. Resolve local force into rotor-axis and in-plane components before connecting it to whole-rotor thrust.','cbt-m1-m1-04','forces');
  add(1,'bigpicture',{task:'Save a reference state. Change collective alone and save a second state; return to the reference and change airspeed alone. Compare thrust, velocity and wake direction.',criterion:'Distinguish rotor thrust direction, aircraft velocity and acceleration tendency.',requirements:[cmp('Collective (total thrust)','Compare collective at the same cyclic, pedals and airspeed.'),cmp('Airspeed V','Compare airspeed with the controls held constant.')],checks:n=>[q('The aircraft has forward velocity while the disc remains level in this simplified model. Which inference is justified?',['Velocity alone does not establish the direction of thrust or net acceleration.','Thrust must point along the aircraft velocity.','The tail rotor supplies all forward force.'],'Thrust follows the rotor orientation. Net force, including drag, determines acceleration; velocity is a different quantity.','cbt-m1-bigpicture','force-velocity')]});
  add(1,'bladeelement',{task:'Work through the four model steps. Keep “Link φ to θ” off. Save a reference, then change pitch alone and inflow alone, saving each state.',criterion:'Explain α = θ − φ and distinguish pitch from angle of attack.',requirements:[cmp('Pitch θ (collective)','Compare pitch alone in the full angle picture.',{step:4,fixed:{'Link φ to θ (realistic)':false}}),cmp('Inflow angle φ','Compare inflow alone in the full angle picture.',{step:4,fixed:{'Link φ to θ (realistic)':false}})],checks:n=>[angleCheck(n)]});
  add(1,'spanwise',{task:'Set blade twist to 0°. At the same RPM, save two stations at least 0.1R apart and compare their local speed.',criterion:'Explain Ωr and the distinction between speed, dynamic pressure and actual local lift.',requirements:[cmp('Blade station r/R','Compare two radial stations at zero twist.',{min:0.1,fixed:{'Blade twist (washout)':'0'}})],checks:n=>{const r=n%2?3:2;return [q(`At unchanged RPM, radius increases by a factor ${r}. With translational velocity neglected, how does dynamic pressure change?`,[`By a factor ${r*r}, because speed increases by ${r}.`,`By a factor ${r}, because pressure is proportional to speed.`,`It stays the same because RPM stays the same.`],'Tangential speed is Ωr; dynamic pressure scales with speed squared. Actual lift also depends on coefficients and area.','cbt-m1-spanwise','radial-speed')];}});
  add(1,'bet-velocity',{id:'cbt-m6-bet-velocity',version:3,title:'Read the velocity triangle around the disc',task:'At the same speed, station and model, save advancing (90°) and retreating (270°) states. Then change speed alone and compare the local velocity triangle.',criterion:'Read the signs and components of local velocity; use the local relative wind to interpret α.',requirements:[cmp('Azimuth ψ','Compare advancing and retreating stations.',{values:['90','270']}),cmp('Forward speed','Compare speed at the same azimuth and station.')],checks:n=>[q('At ψ = 270° with the course CCW convention, what does the translational tangential component do?',['It subtracts from Ωr; local tangential speed is lower.','It adds to Ωr just as on the advancing side.','It makes geometric pitch equal to angle of attack.'],'sin 270° = −1. Interpret the relative-flow triangle separately from geometric pitch.','cbt-m6-bet-velocity','velocity-sign')]});
  add(1,'m1-04',{title:'Build a blade element',mode:'mission',kicker:'CONSTRUCT',task:'Complete the three construction gates: resultant velocity, angle of attack and local force resolution. Save the completed construction.',criterion:'Construct the relative-flow direction and distinguish local force components from whole-rotor thrust.',internalPrediction:true,requirements:[gate(['construction'],'Complete all three construction gates.')],checks:n=>[localForce(n)]});
  add(2,'hover',{title:'Why hover needs power',widget:'wM2HoverWhy',internalPrediction:true,task:'Commit your mechanism in the model before the hover-flow explanation appears. Compare your first choice with the revealed energy transfer.',criterion:'Explain why zero aircraft speed does not mean zero airflow or zero power.',requirements:[gate(['hover-choice'],'Commit the hover mechanism and inspect the reveal.')],checks:n=>[q('In a steady hover, why does induced power remain necessary?',['The rotor continually transfers energy to air moving through the disc.','The aircraft has no velocity, so the rotor has no energy losses.','Power is used only to balance weight without any airflow.'],'Stationary aircraft position does not imply stationary air. Induced power sustains the rotor-induced flow.','cbt-m2-hover','hover-energy')]});
  add(2,'verticalflight',{title:'Collective, thrust and induced flow',widget:'wM2RotorFlowPower',internalPrediction:true,task:'Predict in the model, apply the collective increase, then answer which part of the rotor-flow chain changed first. Save both-state evidence.',criterion:'Separate produced thrust, required hover thrust and acceleration tendency with trim off.',requirements:[gate(['collective-change','first-link'],'Apply the collective change and identify the first causal link.')],checks:n=>[q('With trim off, collective rises and produced thrust exceeds weight. What has changed?',['Produced thrust changed; weight did not, and an upward acceleration tendency results.','Required weight increased because collective increased.','The aircraft must already be climbing at a constant rate.'],'A rotor-state comparison gives thrust and an acceleration tendency. It does not by itself demonstrate the subsequent aircraft trajectory.','cbt-m2-verticalflight','thrust-demand')]});
  add(2,'groundeffect',{title:'Mass and density in trimmed hover',widget:'wM2ChangeDemand',internalPrediction:true,task:'Commit both trimmed comparisons, answer the 15% mass question and complete the heavier-hover causal chain. Save the completed comparison.',criterion:'At trim T ≈ W; distinguish a mass-demand change from a density change at unchanged demand.',requirements:[gate(['mass-comparison','density-comparison','magnitude','causal-chain'],'Complete both comparisons, magnitude and the causal chain.')],checks:n=>[q('Density falls at the same weight and rotor area in trimmed hover. Which chain applies?',['Required thrust stays approximately equal to weight; induced velocity and induced power rise.','Required thrust falls, so induced velocity falls.','Collective sets the aircraft weight, so weight rises.'],'At steady hover T ≈ W. Lower density requires more induced flow for the same thrust; the demand and the trim response are different.','cbt-m2-groundeffect','hover-conditions')]});
  add(2,'groundeffect',{key:'ige-practice',title:'Ground effect at equal thrust',widget:'wCBTGroundEffect',task:'Save a low-height and a high-height state at the same required thrust. Compare induced velocity and induced power.',criterion:'Distinguish equal-thrust IGE/OGE from fixed-collective comparisons.',bodyHtml:'<p>This comparison holds required thrust constant. Change rotor height and compare induced flow and power. A fixed-collective comparison would ask a different question.</p>',takeaways:['In trimmed hover at the same weight, thrust demand is approximately unchanged.','Ground proximity changes the induced-flow cost.'],requirements:[cmp('Rotor height / radius','Compare heights in and outside ground effect.',{min:0.5})],checks:n=>[q('At the same weight, compare steady IGE and OGE hover. What stays approximately equal?',['Required thrust; the induced power cost differs.','Collective and all local flow conditions.','Induced power, because required thrust is equal.'],'Equal required thrust does not imply equal induced velocity or induced power.','cbt-m2-ige-practice','ige-conditions')]});
  add(2,'verticalflight',{key:'axial-practice',title:'Vertical flow and model validity',widget:'wVertical',task:'Use the manual vertical-speed slider to save hover and a descending state. Read the regime labels and identify where the simple momentum model is unreliable.',criterion:'Identify a model-validity boundary without deriving a recovery procedure from the picture.',bodyHtml:'<p>Use the flow-regime labels to compare axial conditions. Near recirculating descent, simple momentum theory is unreliable. This activity concerns flow mechanisms and model validity.</p>',takeaways:['State the sign convention for vertical velocity.','A flow-regime illustration does not supply a type-specific manoeuvre.'],requirements:[cmp('Manual vertical speed V_c','Compare hover and descent.',{descent:true})],checks:n=>[q('A simple momentum model displays a recirculating-descent region. What is justified?',['Its simple-flow assumptions are unreliable there; the picture cannot establish a recovery procedure.','Its computed thrust is exact in every descent regime.','The displayed wake fully resolves turbulence.'],'Recirculation violates the simple clean-streamtube assumptions. Separate an explanatory model from operational instruction.','cbt-m2-axial-practice','flow-validity')]});
  add(3,'dissymmetry',{task:'Save advancing and retreating stations at the same speed. Then change speed alone and compare the local speeds before compensation.',criterion:'Relate Ωr ± V to local dynamic pressure while distinguishing the uncorrected and trimmed rotor.',requirements:[cmp('Azimuth ψ (blade position)','Compare 90° and 270° at the same speed.',{values:['90','270']}),cmp('Forward speed','Compare forward speeds at one azimuth.')],checks:n=>[q('Before compensation, forward speed rises at fixed RPM. What changes?',['Advancing tangential speed rises and retreating tangential speed falls.','Both sides increase by the same amount.','Every station has the same speed because RPM is fixed.'],'The translational component adds to Ωr on one side and subtracts on the other.','cbt-m3-dissymmetry','asymmetry')]});
  add(3,'flapping',{version:3,title:'Why flapping changes angle of attack',task:'A retreating element moves down while pitch stays fixed. Predict its α change. At 60 kt, 270° and 0.75R, save −60°/s and +60°/s flap-rate states. Trace rate → U_P → φ → α.',criterion:'Explain the signed flap-rate contribution at fixed pitch and other flow; distinguish rate from displacement.',requirements:[cmp('Flapping rate β̇','Compare downward and upward rates with the other conditions fixed.',{values:['-60','60'],fixed:{'Forward speed':'60','Azimuth ψ':'270','Blade station r/R':'0.75'}})],checks:n=>[q(`At fixed pitch and positive U_T, ${n%2?'upward':'downward'} blade motion is introduced. Which chain follows?`,[n%2?'Larger U_P → larger φ → smaller α.':'Smaller U_P → smaller φ → larger α.','The vertical component always increases α, regardless of direction.','Flap displacement is added directly to geometric pitch.'],'The signed rate term is r·β̇. Upward motion increases U_P; downward motion decreases it. Use α = θ − φ at unchanged pitch and other flow.','cbt-m3-flapping','signed-rate'),q('A blade reaches a smooth maximum in flapping displacement. What is its instantaneous rate?',['Zero at that instant; a high blade position does not establish a large rate contribution.','Its maximum upward rate.','Its pitch must now equal β.'],'Rate is the derivative of displacement. An extremum is not maximum upward velocity.','cbt-m3-flapping','rate-displacement')]});
  add(3,'bet-guided',{id:'cbt-m7-bet-guided',title:'From rigid blade to flapping and cyclic',task:'At a fixed nonzero speed and station, save the rigid, flapping and cyclic layers at 90°. Then save the cyclic layer at 270°.',criterion:'Separate imposed pitch, flapping velocity and local inflow when interpreting cyclic and α.',requirements:[select(['2 · Rigid fwd','3 · Flapping','4 · Cyclic'],'Compare rigid, flapping and cyclic at the same speed, station and azimuth.',{same:['Forward speed','Azimuth ψ','Blade station r/R'],nonzero:['Forward speed']}),cmp('Azimuth ψ','Compare 90° and 270° in the cyclic layer.',{values:['90','270'],selected:'4 · Cyclic'})],checks:n=>[q('Cyclic changes the pitch distribution. Why does α still vary around the disc?',['α also depends on local tangential, inflow and flapping velocities.','α must equal cyclic pitch everywhere.','Cyclic removes all local-flow differences.'],'Compare θ with the local relative wind at both azimuts. Control input, local aerodynamic angle and rotor response are separate.','cbt-m7-bet-guided','cyclic-flow')]});
  add(3,'flaproll',{task:'Choose Velocity Triangles. Save low- and higher-speed states and compare front/rear inflow. Then inspect Flapback to distinguish the two mechanisms.',criterion:'Trace fore-aft inflow → φ → α → forcing and distinguish inflow roll from longitudinal flapback.',requirements:[cmp('Forward speed','Compare front/rear triangles at two speeds.',{selected:'Velocity Triangles'}),select(['Velocity Triangles','Flapback'],'Inspect both mechanisms.')],checks:n=>[q('At unchanged pitch, the front has less induced downflow than the rear. Which local chain follows?',['Smaller front φ → larger front α → unequal aerodynamic forcing.','Smaller front φ → smaller front α at the same pitch.','Fore-aft inflow changes only geometric pitch.'],'Use α = θ − φ first, then consider the phased rotor response. This fore-aft inflow mechanism differs from speed-driven longitudinal flapback.','cbt-m3-flaproll','inflow-gradient')]});
  add(3,'coriolis',{id:'cbt-m5-coriolis',task:'Save 90° and 270° at the same speed and rotor configuration. Compare flapping and the lead/lag response. Explain the inferred radial mass movement under the model assumptions.',criterion:'Connect changing radial mass position to angular momentum and lead/lag accommodation.',requirements:[cmp('Azimuth ψ (blade position)','Compare two opposite azimuts at fixed configuration.',{values:['90','270']})],checks:n=>[q('A blade mass moves inward, with external torque neglected. What angular-momentum tendency follows?',['Its angular speed tends to rise, producing a lead tendency relative to the rotor.','Its angular speed must fall because radius falls.','Its angular momentum must disappear.'],'Angular momentum IΩ is conserved under the stated assumption. Smaller radial mass distance reduces I and raises the associated angular-speed tendency.','cbt-m5-coriolis','angular-momentum')]});
  add(4,'performance',{task:'Save a reference curve. Change gross weight alone, then restore the reference and change density altitude alone. Compare component and total required power. Explain which additional available-power data would be needed to establish margin.',criterion:'Distinguish power components and matched required versus available power data.',requirements:[cmp('Gross weight','Compare mass with altitude held constant.'),cmp('Density altitude','Compare altitude at the same mass.')],checks:n=>[q('Required power rises while available power stays unchanged at the selected condition. What happens to margin?',['Available minus required power decreases.','Margin increases because demand increased.','Positive margin proves that every other flight limit is satisfied.'],'Compare the two quantities at the same condition and shaft-power reference. The widget plots required power; available power must be supplied separately.','cbt-m4-performance','power-margin')]});
  add(4,'envelope',{version:3,title:'Explain retreating stall and twist',widget:'wLearningWorkspace',models:[['wTwistComparison','1 · Twist in isolation'],['wEnvelope','2 · Rotor diagnostics']],task:'Explain why the first high-α region is not always at the tip. In Twist in isolation, set station to 1R and save 0° and −8° twist with other inputs fixed. Then open Rotor diagnostics and save two speeds with the same preset and station.',criterion:'Separate local α, required loading and assumed critical α; explain what twist alone changes and why actual stall location is conditional.',requirements:[cmp('Blade twist (washout)','Compare zero twist and −8° at the tip, with flow and reference pitch fixed.',{model:'wTwistComparison',values:['0','-8'],fixed:{'Blade station r/R':'1'}}),cmp('Forward speed','Compare two speeds in the same rotor preset.',{model:'wEnvelope'})],checks:n=>[q(`Uniform positive normal flow, no flapping or cyclic, θ fixed along an untwisted blade. Moving outboard at fixed RPM raises U_T. What happens to α?`,['φ decreases, so α increases; an outer region can reach a common α threshold first.','φ increases, so α decreases automatically.','The tip stalls solely because it has the lowest rotational speed.'],'This is a controlled explanation of an outer high-α region, not a universal stall-location rule.','cbt-m4-envelope','untwisted-span'),q(`In the frozen-flow comparison, pitch at 0.75R is fixed. Negative twist is added. What changes?`,['Tip θ and α fall; inboard θ and α rise. The peak can move inward, but its radius depends on the conditions.','Twist must move stall to exactly 0.5R on every rotor.','Twist increases U_T and leaves θ unchanged.'],'At each station φ is held fixed. Δα = Δθ; re-trim, nonuniform inflow and local critical α can alter the real result.','cbt-m4-envelope','twist-causality'),q('A low-loading normal-flow cell exceeds the assumed positive critical α. What can you conclude?',['The model angle threshold is crossed; low loading does not remove it, and actual stalled loads are not solved.','Low dynamic pressure guarantees that its flow cannot separate.','The diagnostic proves aircraft V_NE or a recovery manoeuvre.'],'Keep local angle, aerodynamic load and the limits of the model separate. Advancing compressibility is a separate constraint.','cbt-m4-envelope','diagnostic-limits')]});
  add(5,'dynamicrollover',{task:'Hold the ground pivot and bank angle fixed. Save two collective settings and compare the thrust contribution to rolling moment.',criterion:'Explain the ground-pivot moment and why the illustrative balance threshold is not a safe bank angle.',requirements:[cmp('Collective (thrust)','Compare thrust at the same ground pivot and bank.')],checks:n=>[q('With the same constrained skid and bank angle, rotor thrust increases. What can the pivot model show?',['A larger thrust contribution to the rolling moment; it does not establish recoverability.','A universal safe rollover angle.','An automatic restoring effect in every constrained condition.'],'A contact pivot changes the moment balance. This illustrative comparison omits roll-rate dynamics and control limits.','cbt-m5-dynamicrollover','pivot-moment')]});
  add(5,'lte',{task:'Save two wind directions at the same wind speed and collective. Then compare two collective settings at one wind condition.',criterion:'Distinguish torque demand, available balancing moment and the limits of generic wind-sector models.',requirements:[cmp('Relative wind direction (FROM)','Compare wind direction at fixed demand.'),cmp('Collective (power)','Compare demand at the same wind condition.')],checks:n=>[q('Torque demand increases in steady heading. What balance is needed?',['A corresponding balancing yaw moment within the available control authority.','The same tail-rotor force in every condition.','No anti-torque moment once forward speed is nonzero.'],'Compare demand and available moment. Generic sectors are illustrative and are not aircraft-specific limits.','cbt-m5-lte','yaw-balance')]});
  add(6,'autorotation',{task:'Save two collective settings at fixed speed, inflow and station. Inspect local driving/braking force and the change in region classification.',criterion:'Connect local aerodynamic force direction to driving or braking without treating a fixed-RPM map as a transient energy simulation.',requirements:[cmp('Collective θ₀','Compare collective at fixed flow and station.')],checks:n=>[q('An element is classified as driving in autorotation. What local force effect defines that classification?',['Its in-plane aerodynamic force acts with rotation, supplying driving torque.','Every element supplies positive torque.','Driving torque creates energy without an aircraft energy source.'],'Local driving and braking contributions coexist. Descent and aircraft motion supply the energy budget.','cbt-m6-autorotation','local-torque')]});
  add(6,'autorotation',{key:'energy',title:'Rotor energy: RPM and stored energy',widget:'wRotorEnergy',task:'Save reference RPM and 90% RPM at the same rotor inertia. Compare the available stored energy, then explore another RPM.',criterion:'Use E = ½IΩ² and distinguish an energy state from the rate of energy transfer.',bodyHtml:'<p>Inertia is held constant. Stored rotor energy scales with RPM squared. The diagram compares energy states; it does not simulate a landing or a flare.</p>',takeaways:['90% RPM corresponds to 81% of reference rotational energy.','Torque and aerodynamic power determine how energy changes over time.'],requirements:[cmp('Rotor RPM (% of reference)','Compare reference and 90% RPM.',{values:['100','90']})],checks:n=>{const rpm=n%2?80:90;return [q(`At the same inertia, RPM falls to ${rpm}% of reference. How much reference rotor energy remains?`,[`${rpm*rpm/100}%.`,`${rpm}%.`,'100%, because inertia did not change.'],'E = ½IΩ². An RPM percentage must be squared to obtain the energy fraction.','cbt-m6-energy','rotor-energy')];}});
  const transferSpecs={
    m1:{title:'New blade-element conditions',source:'bladeelement',models:[['wBladeElement','Angles'],['wSpanwise','Radius']],task:'Predict the changed angle, force and radius conditions first. In Angles compare pitch and inflow separately; in Radius compare two stations at zero twist. Use the saved states to explain your decisions.',requirements:[cmp('Pitch θ (collective)','Compare pitch at fixed inflow.',{model:'wBladeElement',step:4,fixed:{'Link φ to θ (realistic)':false}}),cmp('Inflow angle φ','Compare local inflow at fixed pitch.',{model:'wBladeElement',step:4,fixed:{'Link φ to θ (realistic)':false}}),cmp('Blade station r/R','Compare two stations at zero twist.',{model:'wSpanwise',fixed:{'Blade twist (washout)':'0'}})],checks:n=>[angleCheck(n+5),localForce(n),q(`A station moves from ${n%2?'0.2R to 0.6R':'0.4R to 0.8R'} at fixed RPM and density, with other velocity components neglected. What does that establish?`,[n%2?'Speed triples and dynamic pressure increases ninefold; actual lift still depends on coefficients and area.':'Speed doubles and dynamic pressure quadruples; actual lift still depends on coefficients and area.','Speed and actual lift both increase linearly with radius.','Speed remains unchanged because RPM is unchanged.'],'Use Ωr and q = ½ρU². The radial speed evidence alone does not hold the lift coefficient constant.','cbt-m1-spanwise','radial-transfer')]},
    m2:{title:'Changed hover demand and ground proximity',source:'hover',models:[['wHover','Hover demand'],['wCBTGroundEffect','Ground proximity']],task:'Predict the changed demand and equal-thrust ground-effect cases. Save a mass comparison in Hover demand and a height comparison in Ground proximity.',requirements:[cmp('Gross weight','Compare mass with density altitude fixed.',{model:'wHover'}),cmp('Rotor height / radius','Compare height at equal required thrust.',{model:'wCBTGroundEffect',min:0.5})],checks:n=>{const f=[1.21,1.44,1.69][n%3],pct=Math.round((f**1.5-1)*100);return [q(`Ideal OGE hover: mass rises ${Math.round((f-1)*100)}%, with density and area unchanged. Approximate induced-power increase?`,[`About ${pct}%.`,`Exactly ${Math.round((f-1)*100)}%.`,'No change while aircraft speed is zero.'],'Induced power scales with W^(3/2) at fixed density and rotor area. This is the induced term, not all installed power.','cbt-m2-groundeffect','hover-scaling'),q(`At equal weight and required thrust, rotor height changes from ${n%2?'inside ground effect to outside it':'outside ground effect to inside it'}. What happens to the induced-flow cost?`,[n%2?'It rises; thrust demand still remains approximately equal to weight.':'It falls; thrust demand still remains approximately equal to weight.','Weight changes automatically with height.','Equal thrust guarantees equal induced power.'],'Distinguish trimmed equal-thrust and fixed-collective experiments.','cbt-m2-ige-practice','ground-effect')];}},
    m3:{title:'Explain a new rotor response',source:'bet-guided',models:[['wGuidedBET','Rotor layers'],['wFlappingRoll','Inflow mechanisms']],task:'Predict the local-flow effect. Compare rigid and flapping at the same nonzero speed and station, then compare 90° and 270° in the cyclic layer.',requirements:[select(['2 · Rigid fwd','3 · Flapping'],'Compare the rigid and flapping layers at the same condition.',{model:'wGuidedBET',same:['Forward speed','Azimuth ψ','Blade station r/R'],nonzero:['Forward speed']}),cmp('Azimuth ψ','Compare two azimuts in the cyclic layer.',{model:'wGuidedBET',values:['90','270'],selected:'4 · Cyclic'})],checks:n=>[q(`At fixed pitch, ${n%2?'downward':'upward'} flapping changes perpendicular relative velocity. What direct local effect is expected?`,[n%2?'A tendency toward smaller φ and larger α.':'A tendency toward larger φ and smaller α.','Angle of attack must equal pitch.','Only rotor RPM determines α.'],'Flapping rate changes the local relative wind; it is not a change in geometric pitch.','cbt-m3-flapping','flapping-flow'),q(`A cyclic-trimmed element is now at ${n%2?'270° on the retreating side':'90° on the advancing side'}. Which comparison explains its local α?`,['θ together with tangential, inflow and flapping velocities at the same station.','Collective alone.','Aircraft speed alone, without local rotor velocity.'],'Control input, local angle and rotor response must be separated.','cbt-m7-bet-guided','cyclic-response')]},
    m4:{title:'Read changed power and limit evidence',source:'performance',models:[['wPerformance','Power curves'],['wEnvelope','Rotor limits']],task:'Predict the mass and altitude effects. Save both independent power-curve comparisons, then inspect two envelope speeds with unchanged settings.',requirements:[cmp('Gross weight','Compare mass at fixed altitude.',{model:'wPerformance'}),cmp('Density altitude','Compare altitude at fixed mass.',{model:'wPerformance'}),cmp('Forward speed','Compare two speeds in the rotor-limit model.',{model:'wEnvelope'})],checks:n=>{const available=500+n%4*20,required=430+n%3*15;return [q(`Training dataset, one fixed condition: available ${available} kW, required ${required} kW. What is the margin?`,[`${available-required} kW; it is not a check of every other limit.`,`${available+required} kW; add the two values.`,'Positive power margin overrides the approved speed envelope.'],'Power margin is available minus required at the same condition.','cbt-m4-performance','margin'),q(`A supplied speed comparison has induced power ${n%2?'300 → 200':'200 → 150'} kW and parasite power ${n%2?'50 → 100':'100 → 250'} kW; profile power is unchanged. What happens to total required power?`,[n%2?'It falls by 50 kW: combine the component changes.':'It rises by 100 kW: combine the component changes.','It follows the induced-power change alone.','It cannot change while weight stays fixed.'],'Total required power includes induced, profile and parasite terms; compare their combined change.','cbt-m4-performance','power-components'),(()=>{const r=[.9,.6,.95][n%3],change=-8*(r-.75),alpha=(8+change).toFixed(1);return q(`A new frozen-flow case at ${(r*100).toFixed(0)}%R has θ = 12° and φ = 4°. Add −8° linear twist with pitch at 0.75R unchanged. What is the new local α?`,[`${alpha}°: change θ by twist × (r/R − 0.75); φ stays fixed.`,'8.0°: twist never changes local angle of attack.','Exactly 0°: negative twist eliminates retreating stall.'],'Apply the reference-radius relation to this new station. It establishes local α in the supplied frozen-flow case, not an equal-thrust trim or actual stall.','cbt-m4-envelope','twist-transfer');})()];}},
    m5:{title:'Changed pivot and yaw-moment constraints',source:'dynamicrollover',models:[['wDynamicRollover','Ground pivot'],['wLTE','Anti-torque']],task:'Predict both constraint cases. Save two thrust settings at one bank angle in Ground pivot, then two demand settings at one wind condition in Anti-torque.',requirements:[cmp('Collective (thrust)','Compare thrust with the pivot and bank held fixed.',{model:'wDynamicRollover'}),cmp('Collective (power)','Compare torque demand with wind conditions held fixed.',{model:'wLTE'})],checks:n=>[q(`In the stated ground-pivot geometry, the thrust contribution acts in the roll direction. At fixed bank, thrust ${n%2?'decreases':'increases'}. What follows?`,[n%2?'Its driving moment decreases; this alone does not establish recoverability.':'Its driving moment increases; a small bank alone does not establish recoverability.','Only the static tip-over angle matters.','Changing thrust always restores stability.'],'Assess the contact constraint and the contributing moments. The illustrative model does not determine a recovery manoeuvre.','cbt-m5-dynamicrollover','pivot'),q(`Main-rotor torque demand ${n%2?'falls':'rises'} while heading remains steady. What balance must change?`,['The opposing anti-torque and other aerodynamic yaw moments must match the changed demand.','Tail-rotor force must remain identical in every condition.','No moment is needed in forward flight.'],'Demand, available authority and aerodynamic contributions are different quantities.','cbt-m5-lte','anti-torque')]},
    m6:{title:'New torque and rotor-energy states',source:'autorotation',models:[['wAutorotation','Local torque'],['wRotorEnergy','Stored energy']],task:'Predict local torque and energy effects. Save a collective comparison at fixed flow, then reference and 90% RPM at fixed inertia. Use the energy relation to analyse the different supplied RPM.',requirements:[cmp('Collective θ₀','Compare local aerodynamic torque at fixed flow.',{model:'wAutorotation'}),cmp('Rotor RPM (% of reference)','Compare reference and 90% RPM.',{model:'wRotorEnergy',values:['100','90']})],checks:n=>{const rpm=[85,95,80][n%3];return [q(`Engine torque is absent. A supplied whole-rotor state has driving 10 kNm and total resisting ${n%2?'12':'8'} kNm. What torque tendency follows?`,[n%2?'Negative: braking exceeds driving by 2 kNm.':'Positive: driving exceeds braking by 2 kNm.','All blade sections supply positive driving torque.','The rotor generates energy without any source.'],'The supplied resisting total includes other rotor loads. Local torques coexist; connect their net balance to the aircraft energy budget.','cbt-m6-autorotation','torque-balance'),q(`At constant inertia, ${rpm}% reference RPM corresponds to approximately what energy?`,[` ${(rpm*rpm/100).toFixed(1)}% of reference energy.`,`${rpm}% of reference energy.`,'100% regardless of RPM.'],'Stored energy scales with Ω². A fixed-RPM map cannot establish the energy evolution during a manoeuvre.','cbt-m6-energy','energy-budget')];}}
  };
  for(let i=1;i<=6;i++){const spec=transferSpecs['m'+i];add(i,spec.source,{key:'transfer',title:spec.title,mode:'challenge',kicker:'TRANSFER',transfer:true,widget:'wLearningWorkspace',models:spec.models,task:spec.task,criterion:outcomes[i-1],requirements:spec.requirements,checks:spec.checks,bodyHtml:'<p>Commit your reasoning before opening the models. Select the relevant view, save the requested comparisons, then decide. Feedback and earlier attempts remain visible in your record.</p>',takeaways:['A first attempt and a supported retry are recorded separately.','Use model evidence to explain the mechanism and its limits.']});}
  const caseA=n=>{const mass=[1.21,1.44,1.10][n%3],density=[0.81,0.90,0.75][n%3],available=500+n%3*25,required=430+n%3*15,ratio=(mass**1.5/Math.sqrt(density)).toFixed(2),advTheta=7+n%3,advPhi=3,retTheta=11+n%3,retPhi=6;return {
    brief:`An unfamiliar training helicopter must hover after a ${Math.round((mass-1)*100)}% mass increase in air with ${Math.round(density*100)}% of reference density. Rotor area is unchanged. At this changed hover condition, a supplied dataset gives ${available} kW available and ${required} kW required at the same shaft reference. A separate forward-flight snapshot at constant RPM gives local pitch and inflow at opposite azimuts. Analyse ideal induced demand, the supplied total-power margin and local α.`,
    data:[['Mass relative to reference',String(mass)],['Density relative to reference',String(density)],['Rotor area','unchanged'],['Available / required total shaft power',`${available} / ${required} kW; changed hover condition; same reference`],['Forward-flight angle conditions','same radius and RPM; normal chordwise flow'],['Advancing 90°: θ / φ',`${advTheta}° / ${advPhi}°`],['Retreating 270°: θ / φ',`${retTheta}° / ${retPhi}°`]],
    questions:[q(`At mass ratio ${mass} and density ratio ${density}, what ideal-hover induced-power ratio is expected?`,[`About ${ratio} times reference: mass^(3/2) / √density.`,`${mass} times reference: scale with mass alone.`,`${(mass/Math.sqrt(density)).toFixed(2)} times reference: mass / √density.`],'Use the supplied ratios for the numerical estimate. Use separate mass and altitude model comparisons to test directions; altitude is not a direct density-ratio input. This is ideal induced power, not total shaft power.','cbt-m2-groundeffect','combined-demand'),q(`What margin does the matched ${available} / ${required} kW dataset establish?`,[`${available-required} kW at that changed hover condition.`,`${available+required} kW at that changed hover condition.`,`${available-required} kW at every speed with the same aircraft mass.`],'Subtract required from available at the same condition and power reference. The value does not cover every speed or other constraint.','cbt-m4-performance','dataset-margin'),q(`At the same station, advancing θ/φ = ${advTheta}°/${advPhi}° and retreating θ/φ = ${retTheta}°/${retPhi}°. Compare local α.`,[`Advancing ${advTheta-advPhi}°; retreating ${retTheta-retPhi}°: retreating is 1° greater.`,`Advancing ${advTheta+advPhi}°; retreating ${retTheta+retPhi}°: add pitch and inflow.`,`Advancing ${advTheta}°; retreating ${retTheta}°: use pitch alone.`],'Use α = θ − φ at each station. The larger retreating pitch does not translate into the same difference in α because local inflow also differs. Relate this calculation to the saved model triangles.','cbt-m7-bet-guided','integrated-flow')]
  };};
  const caseB=n=>{const rpm=[90,80,95][n%3],driving=[12,8,8][n%3],braking=[8,8,12][n%3],energy=rpm*rpm/100,net=driving-braking,tendency=net>0?'Positive net torque: RPM tends to increase.':net===0?'Zero net torque: RPM is instantaneously unchanged.':'Negative net torque: RPM tends to decrease.',rate=net>0?'increasing':net===0?'instantaneously unchanged':'decreasing';return {
    brief:`Engine torque is absent. A supplied state has ${driving} kNm driving and ${braking} kNm total resisting torque, including aerodynamic and other rotor loads. Inertia is constant. A separate energy-state comparison places the rotor at ${rpm}% of reference RPM. Explain the instantaneous torque tendency, stored energy and what is missing about the earlier history.`,
    data:[['Engine torque','absent'],['Driving / total resisting torque',`${driving} / ${braking} kNm; other rotor loads included`],['RPM states',`100% reference and ${rpm}% case state`],['Rotor inertia','unchanged'],['Prior torque / RPM time history','not supplied']],
    questions:[q(`Engine torque is absent; driving ${driving} kNm and total resisting ${braking} kNm. What instantaneous tendency follows?`,[tendency,net===0?'Negative net torque: engine absence requires RPM decay.':'Zero net torque: autorotation always holds constant RPM.',net>=0?'Negative net torque: driving and resisting contributions cannot balance without the engine.':'Positive net torque: any driving region forces RPM to rise.'],'Sum driving minus all resisting torques. At constant inertia, the net torque determines the instantaneous RPM tendency, not the earlier history. Aircraft energy supplies the unpowered rotor flow.','cbt-m6-autorotation','integrated-torque'),q(`At constant inertia, how much reference rotor energy remains at ${rpm}% RPM?`,[`${energy}%; ${100-energy}% less reference energy.`,`${rpm}%; ${100-rpm}% less reference energy.`,`${(10000/rpm).toFixed(2)}%; energy increases as RPM decreases.`],'Energy scales with RPM squared.','cbt-m6-energy','integrated-energy'),q(`At ${rpm}% RPM and driving/resisting ${driving}/${braking} kNm, what relates the current energy rate to the reference-state difference?`,[`Energy is ${rate} now; the earlier torque history is not established.`,`The energy deficit equals the RPM percentage deficit, independently of torque.`,`The current torque proves that it acted throughout the change from reference.`],'P_net = Q_net Ω gives the instantaneous energy rate for positive RPM. E = ½IΩ² gives the stored energy state. A below-reference value need not be decreasing now, and a snapshot does not establish prior torque.','cbt-m6-energy','integration-limits')]
  };};
  add(7,'performance',{id:'cbt-m7-transfer',title:'Case A — hover demand and transition',mode:'challenge',kicker:'INTEGRATE',transfer:true,scenario:caseA,widget:'wLearningWorkspace',models:[['wHover','Hover demand'],['wPerformance','Power curves'],['wGuidedBET','Rotor response']],task:'First give your analysis of the supplied data. Choose the relevant model views: compare mass and density altitude separately, then compare advancing and retreating stations in the cyclic layer. Use the supplied ratios for the numerical estimate.',criterion:outcomes[6],requirements:[cmp('Gross weight','Test mass demand at fixed altitude.',{model:'wHover'}),cmp('Density altitude','Test thinner-air demand at fixed mass.',{model:'wHover'}),cmp('Azimuth ψ','Compare 90° and 270° in the cyclic layer.',{model:'wGuidedBET',values:['90','270'],selected:'4 · Cyclic'})],checks:n=>caseA(n).questions,bodyHtml:'<p>Choose evidence that answers the problem. The supplied dataset is illustrative training data, not aircraft performance data.</p>',takeaways:['Explain which model addresses each part of the problem.','State the conditions and the limits of your conclusion.']});
  add(7,'autorotation',{key:'energy-case',title:'Case B — aerodynamic torque and stored energy',mode:'challenge',kicker:'INTEGRATE',transfer:true,scenario:caseB,widget:'wLearningWorkspace',models:[['wAutorotation','Aerodynamic torque'],['wRotorEnergy','Rotor energy']],task:'First explain your torque and energy analysis. Compare collective at fixed flow in Aerodynamic torque, then save 100% and the supplied case RPM in Rotor energy. Explain how the two kinds of evidence relate.',criterion:outcomes[6],requirements:[cmp('Collective θ₀','Test local torque at fixed flow.',{model:'wAutorotation'}),cmp('Rotor RPM (% of reference)','Quantify the supplied case energy change.',{model:'wRotorEnergy',values:['100','90'],variantValues:[['100','90'],['100','80'],['100','95']]})],checks:n=>caseB(n).questions,bodyHtml:'<p>These are explanatory state comparisons. Distinguish driving torque, stored energy and an unprovided time history.</p>',takeaways:['Aircraft energy supplies the unpowered rotor flow.','Stored energy and power transfer are different quantities.']});
  const activities=()=>HL_V2_MODULES.flatMap(m=>m.activities);
  activities().forEach(a=>HLProgress.prepare(a.lessonId,a.version));
  function questions(a,n=HLProgress.get(a.lessonId).variant){return a.checks(n).map((item,i)=>({...item,key:'q'+i,id:a.lessonId+'-'+hash(item.prompt+JSON.stringify(item.options))}));}
  function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return (h>>>0).toString(36);}
  function evidence(a,snapshots,n=HLProgress.get(a.lessonId).variant){
    const valid=snapshots.filter(s=>s&&Object.keys(s.values||{}).length);
    return a.requirements.map(r=>{
      const states=valid.filter(s=>(!r.model||s.model===r.model)&&(!r.step||s.state?.step===r.step)&&(!r.selected||(s.selected||[]).includes(r.selected))&&(r.nonzero||[]).every(k=>Math.abs(Number(s.inputs?.[k]))>0.01)&&Object.entries(r.fixed||{}).every(([k,v])=>String(s.inputs[k])===String(v)));
      let passed=false;
      if(r.kind==='gates')passed=states.some(s=>r.keys.every(k=>s.evidence?.gates?.[k]));
      if(r.kind==='selection'){
        const choices=r.options.map(opt=>states.filter(s=>(s.selected||[]).includes(opt)));
        passed=choices.every(c=>c.length>0)&&(!r.same||choices[0].some(base=>choices.every(c=>c.some(s=>r.same.every(k=>s.inputs[k]===base.inputs[k])))));
      }
      if(r.kind==='compare')passed=states.some(x=>states.some(y=>{
        if(x===y||x.model!==y.model)return false;
        const v=Number(x.inputs[r.control]),w=Number(y.inputs[r.control]);
        if(!Number.isFinite(v)||!Number.isFinite(w)||Math.abs(v-w)<(r.min||0.01)-1e-9)return false;
        const requiredValues=r.variantValues?r.variantValues[n%r.variantValues.length]:r.values;
        if(requiredValues&&!requiredValues.every(t=>[String(v),String(w)].includes(t)))return false;
        if(r.descent&&!(Math.abs(v)<0.01&&w<0||Math.abs(w)<0.01&&v<0))return false;
        const keys=new Set([...Object.keys(x.inputs),...Object.keys(y.inputs)]);
        return [...keys].every(k=>k===r.control||x.inputs[k]===y.inputs[k])&&JSON.stringify(x.selected)===JSON.stringify(y.selected);
      }));
      return {label:r.label,passed};
    });
  }
  const complete=a=>{const s=HLProgress.get(a.lessonId);return s.version===a.version&&s.complete&&s.selfReview&&(!a.transfer||a.internalPrediction||!!s.prediction.trim())&&(!a.transfer||!!s.reflection.trim()&&!!s.limitation.trim())&&evidence(a,s.snapshots).every(r=>r.passed)&&questions(a).every(q=>s.decisions[q.key]?.correct&&s.decisions[q.key].question===q.id);};
  const status=a=>complete(a)?'Complete':HLProgress.get(a.lessonId).viewed?'In progress':HLProgress.get(a.lessonId).prior?'Updated task · previous work saved':'Not started';
  const next=()=>activities().find(a=>!complete(a))||null;
  const independent=a=>{const s=HLProgress.get(a.lessonId);return complete(a)&&questions(a).every(q=>s.decisions[q.key]?.correct&&!s.decisions[q.key]?.assisted);};
  // A local observation applies to the actual observed case, not every case in a module.
  const stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
  function observationContext(a){
    const s=HLProgress.get(a.lessonId);
    const work={task:a.task,criterion:a.criteria,requirements:a.requirements,questions:questions(a).map(q=>q.id),version:s.version,variant:s.variant,prediction:s.prediction,reflection:s.reflection,limitation:s.limitation,decisions:s.decisions,snapshots:s.snapshots,selfReview:s.selfReview,complete:complete(a)};
    return {activityId:a.lessonId,taskVersion:a.version,variant:s.variant,evidenceKey:hash(JSON.stringify(stable(work))),rubricVersion:RUBRIC_VERSION};
  }
  function observation(m){
    const review=HLProgress.all().reviews[m.id];
    if(!review)return {current:false,label:'No local observation saved'};
    const a=m.activities.find(a=>a.lessonId===review.activityId);
    if(!a||!review.evidenceKey||review.version!==VERSION||review.rubricVersion!==RUBRIC_VERSION)return {current:false,label:'Earlier observation retained — confirm the observed activity and evidence again'};
    const context=observationContext(a);
    if(review.taskVersion!==context.taskVersion||review.variant!==context.variant||review.evidenceKey!==context.evidenceKey)return {current:false,label:'Observed case or evidence changed — earlier observation retained; a new observation is needed'};
    const counts=Object.fromEntries(['independent','supported','discuss','unobserved'].map(v=>[v,reviewCriteria.filter(c=>(review.criteria?.[c.key]||'unobserved')===v).length]));
    return {current:true,activity:a,counts,label:`Observed case: ${a.title} · case ${context.variant+1}. Criteria: ${counts.independent} independent, ${counts.supported} with support, ${counts.discuss} need discussion, ${counts.unobserved} not observed.`};
  }
  return {VERSION,activities,questions,evidence,complete,status,next,independent,reviewCriteria,observationContext,observation,lessons:()=>lessons};
})();
