const assert=require('node:assert/strict');const {setup}=require('./browser-helper.cjs');
(async()=>{const h=await setup();try{
 const {page,go,predict,capture,control,choose,shot}=h;let passed=0;const ok=(name,value)=>{assert.ok(value,name);passed++;console.log('PASS '+name);};
 await page.addInitScript(()=>{window.__observers=[];const O=ResizeObserver;window.ResizeObserver=class extends O{constructor(fn){super(fn);__observers.push(this);}disconnect(){this.closed=true;super.disconnect();}};window.__ticks=0;const si=setInterval;window.setInterval=(fn,ms)=>si(()=>{__ticks++;fn();},ms);});
 await go('home');await shot('path-desktop');
 await go('activity/cbt-m1-spanwise');await go('home');ok('Continue still points to the earliest open activity',await page.getByText('Next recommended step: 1.1',{exact:false}).count()===1);
 await go('activity/cbt-m1-bigpicture');await page.locator('.cbt-activity-footer .primary').click();ok('Footer does not bypass unfinished work',page.url().endsWith('cbt-m1-bigpicture')&&await page.evaluate(()=>!HLProgress.get('cbt-m1-bigpicture').complete));
 await go('activity/cbt-m2-groundeffect');await page.getByRole('button',{name:'Thinner air',exact:true}).click();await capture();ok('Switching a native tab cannot pass the demand task',await page.getByRole('button',{name:'Check your reasoning',exact:true}).isDisabled());
 // Complete the native three-gate mission through the keyboard controls.
 async function native(id){
  if(id==='cbt-m1-m1-04'){const next=page.locator('.hl-step-nav button').last();await next.click();ok('Construction remains locked before commit',await next.isDisabled());await page.getByLabel('V_rel start point',{exact:true}).selectOption('wind');await page.getByLabel('V_rel end point',{exact:true}).selectOption('element');await page.getByRole('button',{name:'Construct from endpoints',exact:true}).click();await page.getByRole('button',{name:'Commit V_rel construction',exact:true}).click();await next.click();await page.reload();await page.waitForFunction(()=>window.HLApp);ok('Construction resumes at the committed angle step',await page.evaluate(()=>document.querySelector('.hl-widget-mount')._hlModel.get().step===3));await page.getByRole('radio',{name:'α = 6°',exact:true}).click();await next.click();await next.click();await page.getByRole('radio',{name:/local normal component contributes/i}).click();await next.click();await page.locator('.hl-widget-mount').scrollIntoViewIfNeeded();await shot('construction-desktop');}
  if(id==='cbt-m2-hover')await page.locator('.hl-w-controls .hl-check-opt').nth(1).click();
  if(id==='cbt-m2-verticalflight'){await page.locator('.hl-w-controls .hl-check-opt').first().click();ok('Native prediction is neutral before the control change',await page.locator('.hl-w-controls .hl-check-opt.correct,.hl-w-controls .hl-check-opt.wrong').count()===0);await page.getByRole('button',{name:'Increase collective',exact:true}).click();await page.getByRole('button',{name:'Produced thrust',exact:true}).click();}
  if(id==='cbt-m2-groundeffect'){await page.getByRole('button',{name:'Heavier hover',exact:true}).click();await page.locator('.hl-w-controls .hl-check-opt').first().click();await page.getByRole('button',{name:'25%',exact:true}).click();await page.getByRole('button',{name:'Thinner air',exact:true}).click();await page.locator('.hl-w-controls .hl-check-opt').first().click();await page.getByRole('button',{name:'Heavier hover',exact:true}).click();for(const text of ['required thrust increases','induced velocity increases','induced power increases','rotor transfers more energy to the air'])await page.getByRole('button',{name:text,exact:true}).click();await page.getByRole('button',{name:'Check chain',exact:true}).click();await page.reload();await page.waitForFunction(()=>window.HLApp);ok('All native demand commitments survive reload',await page.evaluate(()=>document.querySelector('.hl-widget-mount')._hlModel.evidence().gates['causal-chain']));}
  await capture();
 }
 async function modelEvidence(a){
  if(a.internalPrediction){await native(a.lessonId);return;}
  for(const r of a.requirements){
   if(r.model)await page.locator('.hl-workspace-views button[data-model="'+r.model+'"]').click();
   if(r.step){for(let i=0;i<3;i++){const n=await page.locator('.hl-widget-mount').evaluate(host=>host._hlModel.get().step||host.querySelector('.hl-workspace-model')?._hlModel?.get().step);if(n===r.step)break;await page.locator('.hl-step-nav button').last().click();}}
   for(const [label,value] of Object.entries(r.fixed||{}))await control(label,value);
   for(const label of r.nonzero||[])await control(label,40);
   if(r.selected)await choose(r.selected);
   if(r.kind==='selection'){for(const option of r.options){await choose(option);for(const label of r.same||[])if(label==='Forward speed')await control(label,40);await capture();}}
   if(r.kind==='compare'){
    const bounds=await page.locator('.hl-widget-mount').evaluate((host,label)=>{const e=[...host.querySelectorAll('input')].find(e=>e.getAttribute('aria-label')===label);if(!e)throw Error('Missing '+label);return {value:+e.value,min:+e.min,max:+e.max,step:+e.step||1};},r.control);
    let values=r.values?.map(Number)|| (r.descent?[0,-2]:[bounds.value,bounds.value+(Math.max(r.min||0,bounds.step*2)||1)*(bounds.value+Math.max(r.min||0,bounds.step*2)>bounds.max?-1:1)]);
    for(const value of values){await control(r.control,value);await capture();}
   }
  }
 }
 const ids=await page.evaluate(()=>HLTraining.activities().map(a=>a.lessonId));
 for(const id of ids){
  await go('activity/'+id);const a=await page.evaluate(id=>{const a=HLTraining.activities().find(a=>a.lessonId===id);return {lessonId:id,requirements:a.requirements,internalPrediction:a.internalPrediction,transfer:a.transfer};},id);await predict();await modelEvidence(a);
  ok('Actual model evidence meets '+id,await page.evaluate(id=>HLTraining.evidence(HLTraining.activities().find(a=>a.lessonId===id),HLProgress.get(id).snapshots).every(r=>r.passed),id));
  await page.getByRole('button',{name:'Check your reasoning',exact:true}).click();
  const checks=page.locator('.cbt-case');
  if(id==='cbt-m1-m1-04'){await checks.first().locator('input[value="1"]').check();await checks.first().getByRole('button',{name:'Commit decision',exact:true}).click();await checks.first().getByRole('button',{name:'Retry after feedback',exact:true}).click();}
  for(let i=0;i<await checks.count();i++){await checks.nth(i).locator('input[value="0"]').check();await checks.nth(i).getByRole('button',{name:'Commit decision',exact:true}).click();}
  const complete=page.getByRole('button',{name:'Complete this activity',exact:true});ok('Checks alone do not complete '+id,await complete.isDisabled());
  if(a.transfer){await page.getByLabel('Explain your conclusion using the saved evidence.',{exact:false}).fill('The saved states hold the other controls constant. They expose the changed local flow or moment. I distinguish imposed controls from the model response and connect the causal steps to the case.');await page.getByLabel('State one assumption, missing piece',{exact:false}).fill('The state model does not provide a trajectory or aircraft operating approval.');}
  await page.locator('.cbt-option input[type=checkbox]').check();await complete.click();ok('Task completes from required evidence '+id,await page.evaluate(id=>HLTraining.complete(HLTraining.activities().find(a=>a.lessonId===id)),id));
  if(id==='cbt-m1-m1-04'){ok('Supported retry stays distinct',await page.evaluate(()=>HLProgress.get('cbt-m1-m1-04').decisions.q0.assisted&&HLProgress.get('cbt-m1-m1-04').attempts.some(a=>a.kind==='decision'&&!a.correct)));}
  if(id==='cbt-m1-transfer'){await page.locator('.cbt-activity-footer .primary').click();ok('Module end opens its result instead of free exploration',page.url().endsWith('/module/m1/result'));await page.waitForFunction(()=>document.querySelector('#hlMain').dataset.route==='#/module/m1/result');await shot('module-result-desktop');}
  if(id==='cbt-m6-autorotation'){await page.getByRole('button',{name:'Review saved work',exact:true}).click();await page.locator('.cbt-phases [data-phase=model]').click();await control('Collective θ₀',5);ok('Torque comparison resolves driving dominance at the reference flow',await page.locator('.hl-kv').filter({hasText:'Aerodynamic torque tendency'}).textContent().then(s=>s.includes('positive')));await control('Collective θ₀',9);ok('High-pitch comparison resolves braking dominance including stalled cells',await page.locator('.hl-kv').filter({hasText:'Aerodynamic torque tendency'}).textContent().then(s=>s.includes('negative')));}
  if(id==='cbt-m6-energy'){await page.getByRole('button',{name:'Review saved work',exact:true}).click();await page.locator('.cbt-phases [data-phase=model]').click();await control('Rotor RPM (% of reference)',90);ok('Actual energy model shows 81% at 90% RPM',await page.locator('.hl-kv').filter({hasText:'Stored rotor energy'}).textContent().then(s=>s.includes('81.0%')));}
  if(id==='cbt-m7-transfer'){await page.getByRole('button',{name:'Review saved work',exact:true}).click();await shot('integration-check-desktop');await page.reload();await page.waitForFunction(()=>window.HLApp);await page.getByRole('button',{name:'Review saved work',exact:true}).click();ok('Committed options and self-review reappear after reload',await page.locator('.cbt-case input:checked').count()===3&&await page.locator('.cbt-option input[type=checkbox]').isChecked());}
 }
 await go('home');ok('Completed course has a summary and no invented next task',await page.getByRole('button',{name:'View course summary',exact:true}).count()===1&&await page.evaluate(()=>HLTraining.next()===null));await go('finish');await shot('course-summary-desktop');
 // Persistence across model switching and reload; snapshots must not mutate.
 await go('activity/cbt-m7-transfer');await page.getByRole('button',{name:'Review saved work',exact:true}).click();await page.locator('.cbt-phases [data-phase=model]').click();await page.locator('.hl-workspace-views button[data-model=wHover]').click();await control('Gross weight',3200);await capture();const first=await page.evaluate(()=>JSON.stringify(HLProgress.get('cbt-m7-transfer').snapshots[0]));await page.locator('.hl-workspace-views button[data-model=wGuidedBET]').click();await choose('4 · Cyclic');await control('Azimuth ψ',270);await page.reload();await page.waitForFunction(()=>window.HLApp);ok('Active workspace and azimuth resume exactly',await page.locator('.hl-workspace-views button[data-model=wGuidedBET]').getAttribute('aria-pressed')==='true'&&await page.getByLabel('Azimuth ψ',{exact:true}).inputValue()==='270');await page.locator('.hl-workspace-views button[data-model=wHover]').click();ok('Inactive model controls resume when selected',await page.getByLabel('Gross weight',{exact:true}).inputValue()==='3200');ok('Earlier saved snapshots are immutable',await page.evaluate(()=>JSON.stringify(HLProgress.get('cbt-m7-transfer').snapshots[0]))===first);
 // Changed cases retain attempts, replace conditions and retire completion.
 await page.locator('.cbt-phases [data-phase=check]').click();const old=await page.evaluate(()=>({questions:HLTraining.questions(HLTraining.activities().find(a=>a.lessonId==='cbt-m7-transfer')).map(q=>q.id),attempts:HLProgress.get('cbt-m7-transfer').attempts.length}));await page.getByRole('button',{name:'Start a new changed case',exact:true}).click();await page.waitForFunction(()=>HLProgress.get('cbt-m7-transfer').variant===1);ok('New integrated case changes all questions and keeps previous work',await page.evaluate(old=>{const a=HLTraining.activities().find(a=>a.lessonId==='cbt-m7-transfer'),s=HLProgress.get(a.lessonId);return !s.complete&&s.attempts.length>old.attempts&&HLTraining.questions(a).every((q,i)=>q.id!==old.questions[i]);},old));
 await page.setViewportSize({width:390,height:844});await go('home');await shot('path-mobile');await go('activity/cbt-m7-energy-case');await page.getByRole('button',{name:'Review saved work',exact:true}).click();await shot('energy-case-mobile');
 const backup=await page.evaluate(()=>HLProgress.export());await go('record');await page.locator('summary').filter({hasText:'Instructor / peer'}).first().click();await page.getByLabel('Reviewer name',{exact:true}).first().fill('Test observer');await page.getByLabel('Observed reasoning,',{exact:false}).first().fill('Observed a changed case; the learner required one prompt on the limit.');await page.getByLabel('States an assumption,',{exact:false}).first().selectOption('supported');await page.getByRole('button',{name:'Save observation',exact:true}).first().click();await page.reload();await page.waitForFunction(()=>window.HLApp);ok('Reviewer criteria persist separately from completion',await page.evaluate(()=>HLProgress.all().reviews.m1.criteria.limits==='supported'));
 const before=await page.evaluate(()=>HLProgress.export());await page.getByLabel('Import learning record backup',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});ok('Invalid backup does not change current work',await page.evaluate(()=>HLProgress.export())===before);
 page.once('dialog',d=>d.accept());await page.getByLabel('Import learning record backup',{exact:true}).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});await page.waitForTimeout(100);ok('Valid backup retains explanations and limitations',await page.evaluate(()=>HLProgress.get('cbt-m7-energy-case').limitation.length>0&&HLProgress.get('cbt-m7-energy-case').complete));
 // Switch routes without full reload to observe lifecycle cleanup.
 await go('lesson/bet-guided');await page.getByRole('button',{name:'Play or pause azimuth sweep'}).click();await page.waitForTimeout(200);await page.evaluate(()=>location.hash='#/module/m1');await page.waitForTimeout(100);const ticks=await page.evaluate(()=>__ticks);await page.waitForTimeout(400);ok('Timer stops after leaving the animated model',await page.evaluate(()=>__ticks)===ticks);ok('All departed model observers disconnect',await page.evaluate(()=>__observers.every(o=>o.closed)));
 const fallback=await h.browser.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(k,...args){return k.startsWith('webgl')?null:get.call(this,k,...args);};});await fallback.goto(h.url+'#/rotor-lab');await fallback.waitForTimeout(200);ok('No-WebGL fallback provides 2D learning',await fallback.locator('.hl-sb-3d-fallback a').count()>0);await fallback.close();
 const blocked=await h.browser.newPage();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}}));await blocked.goto(h.url+'#/record');ok('Unavailable storage is disclosed',await blocked.getByText('Storage unavailable:',{exact:false}).count()>0);await blocked.close();
 page.once('dialog',d=>d.accept());await page.locator('#hlResetBtn').click();await page.waitForFunction(()=>document.querySelector('#hlMain').dataset.route==='#/home');await go('activity/cbt-m1-bigpicture');await predict();const resetTask=await page.evaluate(()=>{const a=HLTraining.activities()[0];return {lessonId:a.lessonId,requirements:a.requirements};});await modelEvidence(resetTask);await page.getByRole('button',{name:'Check your reasoning',exact:true}).click();await page.locator('.cbt-case input[value="0"]').check();await page.getByRole('button',{name:'Commit decision',exact:true}).click();await page.locator('.cbt-option input[type=checkbox]').check();await page.getByRole('button',{name:'Complete this activity',exact:true}).click();ok('A reset session can complete a correctly versioned task',await page.evaluate(()=>HLTraining.complete(HLTraining.activities()[0])));
 ok('No uncaught application errors',h.errors.length===0);console.log(`${passed} browser acceptance checks passed`);
 }finally{await h.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
