const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch(e){res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__observers=[];const Original=ResizeObserver;window.ResizeObserver=class extends Original{constructor(fn){super(fn);window.__observers.push(this);}disconnect(){this.closed=true;super.disconnect();}};window.__ticks=0;const si=setInterval;window.setInterval=(fn,ms)=>si(()=>{window.__ticks++;fn();},ms);});
const url=`http://127.0.0.1:${server.address().port}/HeliLab.html`;
const go=async id=>{await page.goto(url+'#/'+id);await page.waitForTimeout(350);};
const predict=async()=>{await page.getByLabel('Before you explore:',{exact:false}).fill('I expect increased loading to change the relative wind and required rotor force.');await page.getByRole('button',{name:/Save prediction and open|Update prediction/}).click();};
let passed=0;const ok=(name,value)=>{assert.ok(value,name);passed++;console.log('PASS '+name);};
await go('activity/cbt-m1-bigpicture');await page.locator('.hl-lesson-foot .primary').click();
ok('Navigation does not complete practice',await page.evaluate(()=>!HLProgress.get('cbt-m1-bigpicture').complete));
await go('activity/cbt-m1-m1-04');await predict();
const next=page.locator('.hl-step-nav button').last();await next.click();ok('Construction gate blocks next',await next.isDisabled());
await page.getByLabel('V_rel start point',{exact:true}).selectOption('wind');await page.getByLabel('V_rel end point',{exact:true}).selectOption('element');await page.getByRole('button',{name:'Construct from endpoints',exact:true}).click();await page.getByRole('button',{name:'Commit V_rel construction',exact:true}).click();await next.click();
await page.getByRole('radio',{name:'α = 6°',exact:true}).click();await next.click();await next.click();
await page.getByRole('radio',{name:/local normal component contributes/i}).click();await next.click();
if(process.env.HL_QA_DIR){fs.mkdirSync(process.env.HL_QA_DIR,{recursive:true});await page.locator('.hl-widget-mount').screenshot({path:path.join(process.env.HL_QA_DIR,'mission-completed-desktop.png')});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);await page.locator('.hl-widget-mount').screenshot({path:path.join(process.env.HL_QA_DIR,'mission-completed-mobile.png')});await page.setViewportSize({width:1280,height:900});}
ok('Keyboard construction records gate evidence',await page.evaluate(()=>HLProgress.get('cbt-m1-m1-04').attempts.some(a=>a.kind==='construction'&&a.correct)));
await page.getByLabel('Record your comparison:',{exact:false}).fill('The resultant joins the airflow tip to the element. θ is 10 degrees and φ is 4, leaving α at 6 degrees.');await page.getByRole('button',{name:'Save observation',exact:true}).click();
// Exercise wrong answer, feedback, retry and supported response.
let box=page.locator('.cbt-case').filter({has:page.locator('input[type=radio]')}).first();
const answer=await page.evaluate(()=>HL_LESSONS.find(l=>l.id==='m1-04').check?.answer??0);
await box.locator(`input[value="${(answer+1)%3}"]`).check();await box.getByRole('button',{name:'Commit decision',exact:true}).click();await box.getByRole('button',{name:'Try this decision again',exact:true}).click();box=page.locator('.cbt-case').filter({has:page.locator('input[type=radio]')}).first();await box.locator(`input[value="${answer}"]`).check();await box.getByRole('button',{name:'Commit decision',exact:true}).click();
const complete=page.getByRole('button',{name:'Complete this activity',exact:true});ok('A correct decision alone cannot complete the task',await complete.isDisabled());
await page.getByLabel('Explain your result,',{exact:false}).fill('Lift acts normal to relative airflow, not the chord. Its resolved normal component contributes to thrust, while the in-plane component opposes rotation. This is one fixed local blade element, not the whole rotor.');await page.getByLabel('I compared my explanation',{exact:false}).check();await complete.click();
ok('Evidence plus reflection and self-review completes practice',await page.evaluate(()=>HLProgress.get('cbt-m1-m1-04').complete));
await page.reload();ok('Completion persists after reload',await page.evaluate(()=>HLProgress.get('cbt-m1-m1-04').complete));
await go('activity/cbt-m2-verticalflight');await predict();await page.locator('.hl-w-controls .hl-check-opt').nth(1).click();ok('Prediction stays neutral before observation',await page.locator('.hl-w-controls .hl-check-opt.correct,.hl-w-controls .hl-check-opt.wrong').count()===0);await page.getByRole('button',{name:'Increase collective',exact:true}).click();ok('Feedback appears after applying change',await page.locator('.hl-w-controls .hl-check-opt.correct').count()===1);
await go('activity/cbt-m7-transfer');await predict();const cases=page.locator('.cbt-case').filter({has:page.locator('input[type=radio]')});for(let i=0;i<2;i++){await cases.nth(i).locator('input[value="0"]').check();await cases.nth(i).getByRole('button',{name:'Commit decision',exact:true}).click();}await page.getByLabel('Explain your result,',{exact:false}).fill('Greater weight increases hover induced power while lower density increases it further. I would compare required and available power using approved aircraft data; the model alone cannot establish operational margins.');await page.getByLabel('I compared my explanation',{exact:false}).check();await page.getByRole('button',{name:'Complete this activity',exact:true}).click();ok('Two changed cases with explanation complete transfer',await page.evaluate(()=>HLProgress.get('cbt-m7-transfer').complete));
const backup=await page.evaluate(()=>HLProgress.export());await go('record');await page.locator('summary').filter({hasText:'Instructor / peer'}).first().click();await page.getByLabel('Reviewer name',{exact:true}).first().fill('Test instructor');await page.getByLabel('Observed reasoning,',{exact:false}).first().fill('Explained signs independently; next compare a second inflow angle.');await page.getByRole('button',{name:'Save observation',exact:true}).first().click();ok('Instructor observation is stored separately',await page.evaluate(()=>HLProgress.all().reviews.m1.reviewer==='Test instructor'));
const before=await page.evaluate(()=>HLProgress.export());await page.getByLabel('Import learning record backup',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});ok('Malformed backup leaves record intact',await page.evaluate(()=>HLProgress.export())===before);
page.once('dialog',d=>d.accept());await page.getByLabel('Import learning record backup',{exact:true}).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});await page.waitForTimeout(100);ok('Backup restores practice and transfer',await page.evaluate(()=>HLProgress.get('cbt-m1-m1-04').complete&&HLProgress.get('cbt-m7-transfer').complete));
await go('lesson/bet-guided');await page.getByRole('button',{name:'Play or pause azimuth sweep'}).click();await page.waitForTimeout(300);await go('module/m1');const ticks=await page.evaluate(()=>__ticks);await page.waitForTimeout(500);ok('Azimuth timer stops after leaving widget',await page.evaluate(()=>__ticks)===ticks);ok('All old resize observers disconnect on module route',await page.evaluate(()=>__observers.every(o=>o.closed)));
const out=process.env.HL_QA_DIR;if(out){fs.mkdirSync(out,{recursive:true});await go('home');await page.screenshot({path:path.join(out,'home-desktop.png')});await go('activity/cbt-m1-m1-04');await predict();await page.screenshot({path:path.join(out,'mission-desktop.png')});await page.setViewportSize({width:390,height:844});await go('activity/cbt-m2-ige-practice');await predict();await page.locator('.hl-widget-mount').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'ground-effect-mobile.png')});await go('record');await page.screenshot({path:path.join(out,'record-mobile.png')});}
const fallback=await browser.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(k,...args){return k.startsWith('webgl')?null:get.call(this,k,...args);};});await fallback.goto(url+'#/rotor-lab');await fallback.waitForTimeout(200);ok('No-WebGL fallback offers a working 2D learning route',await fallback.locator('.hl-sb-3d-fallback a').count()>0);await fallback.close();
const blocked=await browser.newPage();await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}});});await blocked.goto(url+'#/record');ok('Blocked storage is disclosed in learning record',await blocked.getByText('Storage unavailable:',{exact:false}).count()>0);await blocked.close();
ok('No uncaught application errors',errors.length===0);
console.log(`${passed} browser acceptance checks passed`);await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
