'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');let count=0;
function load(storage={getItem:()=>null,setItem:()=>{}}){const context=vm.createContext({localStorage:storage});for(const f of ['helilab_content.js','helilab_progress.js','helilab_training.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);return vm.runInContext('({HLProgress,HLTraining,HL_V2_MODULES})',context);}
function test(name,fn){fn();count++;console.log('PASS '+name);}
const {HLProgress:p,HLTraining:t,HL_V2_MODULES:modules}=load(),all=t.activities();
const act=id=>all.find(a=>a.lessonId===id);
function state(inputs,extra={}){return {model:'test',inputs,selected:[],values:{result:'1'},state:{step:4},evidence:{},...extra};}
function evidenceStates(a){const out=[];for(const r of a.requirements){const model=r.model||a.widget,inputs={...(r.fixed||{})};for(const k of r.same||[])inputs[k]='10';for(const k of r.nonzero||[])inputs[k]='10';if(r.kind==='gates')out.push(state(inputs,{model,evidence:{gates:Object.fromEntries(r.keys.map(k=>[k,true]))}}));if(r.kind==='compare'){const values=r.values|| (r.descent?['0','-2']:['0','2']);for(const v of values)out.push(state({...inputs,[r.control]:v},{model,selected:r.selected?[r.selected]:[]}));}if(r.kind==='selection')for(const opt of r.options)out.push(state(inputs,{model,selected:[opt]}));}return out;}
function finish(a){p.patch(a.lessonId,{version:a.version,complete:true,selfReview:true,prediction:'Reasoned prediction',reflection:'Explanation with saved evidence',limitation:'Fixed conditions',snapshots:evidenceStates(a),decisions:Object.fromEntries(t.questions(a).map(q=>[q.key,{choice:q.answer,correct:true,assisted:false,question:q.id}]))});}
test('Seven ordered modules with 29 unique, stable IDs',()=>{assert.equal(modules.length,7);assert.equal(all.length,29);assert.equal(new Set(all.map(a=>a.lessonId)).size,29);for(const m of modules){assert.ok(m.available&&m.outcome);assert.ok(m.activities.some(a=>a.transfer));}for(const a of all)assert.equal(t.lessons().filter(l=>l.id===a.lessonId).length,1);});
test('Prerequisite velocity and rotor-response tasks precede integration',()=>{assert.ok(modules[0].activities.some(a=>a.lessonId==='cbt-m6-bet-velocity'));assert.ok(modules[2].activities.some(a=>a.lessonId==='cbt-m7-bet-guided'));assert.ok(modules[2].activities.some(a=>a.lessonId==='cbt-m5-coriolis'));assert.ok(modules[6].activities.every(a=>a.transfer&&a.scenario));});
test('Each task defines explicit evidence and its own questions',()=>{for(const a of all){assert.ok(a.task&&a.criteria&&a.requirements.length&&typeof a.checks==='function');for(const q of t.questions(a)){assert.ok(q.prompt&&q.why&&q.criterion&&q.options[q.answer]);assert.equal(new Set(q.options).size,q.options.length);assert.ok(act(q.revisit));}}});
test('No task completes from an empty comparison or a stored flag',()=>{for(const a of all){assert.ok(t.evidence(a,[]).some(r=>!r.passed));p.patch(a.lessonId,{complete:true});assert.equal(t.complete(a),false);}});
test('Every contract admits a controlled evidence comparison',()=>{for(const a of all)assert.ok(t.evidence(a,evidenceStates(a)).every(r=>r.passed),a.lessonId);});
test('Identical snapshots and simultaneous changes do not pass',()=>{const a={requirements:[{kind:'compare',control:'speed',label:'speed'}]},x=state({speed:'1',mass:'10'});assert.equal(t.evidence(a,[x,{...x}])[0].passed,false);assert.equal(t.evidence(a,[x,state({speed:'2',mass:'11'})])[0].passed,false);assert.equal(t.evidence(a,[x,state({speed:'2',mass:'10'})])[0].passed,true);});
test('Selected layer and fixed conditions are enforced',()=>{const a={requirements:[{kind:'compare',control:'pitch',label:'pitch',selected:'cyclic',fixed:{link:false},step:4}]};assert.equal(t.evidence(a,[state({pitch:'1',link:true},{selected:['cyclic']}),state({pitch:'2',link:true},{selected:['cyclic']})])[0].passed,false);assert.equal(t.evidence(a,[state({pitch:'1',link:false},{selected:['cyclic']}),state({pitch:'2',link:false},{selected:['cyclic']})])[0].passed,true);});
test('Minimum radial separation tolerates floating point representation',()=>{const a={requirements:[{kind:'compare',control:'r',min:.1}]};assert.equal(t.evidence(a,[state({r:'.75'}),state({r:'.85'})])[0].passed,true);});
test('Native demand cannot pass without every required gate',()=>{const a=act('cbt-m2-groundeffect');const keys=a.requirements[0].keys;for(const missing of keys){const gates=Object.fromEntries(keys.map(k=>[k,k!==missing]));assert.equal(t.evidence(a,[state({},{evidence:{gates}})])[0].passed,false);}});
test('Hover and descent must include zero and a negative state',()=>{const a=act('cbt-m2-axial-practice');assert.equal(t.evidence(a,[state({'Manual vertical speed V_c':'1'}),state({'Manual vertical speed V_c':'2'})])[0].passed,false);});
test('Rotor layers must be compared at the same nonzero condition',()=>{const a=act('cbt-m7-bet-guided'),states=evidenceStates(a);states.forEach(s=>s.inputs['Forward speed']='0');assert.equal(t.evidence(a,states)[0].passed,false);});
test('Correct checks still require prediction, evidence and self-review',()=>{const a=all[0];finish(a);assert.equal(t.complete(a),true);for(const fields of [{prediction:''},{snapshots:[]},{selfReview:false},{version:1}]){finish(a);p.patch(a.lessonId,fields);assert.equal(t.complete(a),false);}});
test('Transfer additionally requires an explanation and stated limitation',()=>{const a=act('cbt-m1-transfer');finish(a);assert.equal(t.complete(a),true);p.patch(a.lessonId,{limitation:''});assert.equal(t.complete(a),false);});
test('Old question IDs cannot pass a changed case',()=>{const a=act('cbt-m7-transfer');finish(a);p.patch(a.lessonId,{variant:1});assert.equal(t.complete(a),false);});
test('Capstone variants change supplied conditions and every question',()=>{for(const id of ['cbt-m7-transfer','cbt-m7-energy-case']){const a=act(id);assert.notEqual(a.scenario(0).brief,a.scenario(1).brief);const first=t.questions(a,0);t.questions(a,1).forEach((q,i)=>assert.notEqual(q.id,first[i].id));}});
test('Each transfer offers changed first and second checks on a new variant',()=>{for(const a of all.filter(a=>a.transfer)){const before=t.questions(a,0);t.questions(a,1).forEach((q,i)=>assert.notEqual(q.id,before[i].id,a.lessonId));}});
test('Energy case requires the RPM supplied by its current variant',()=>{const a=act('cbt-m7-energy-case'),states=evidenceStates(a);assert.equal(t.evidence(a,states,1)[1].passed,false);states.forEach(s=>{if(s.inputs['Rotor RPM (% of reference)']==='90')s.inputs['Rotor RPM (% of reference)']='80';});assert.equal(t.evidence(a,states,1)[1].passed,true);});
test('Integrated hover scaling and energy answers match the data',()=>{const a=act('cbt-m7-transfer');assert.ok(t.questions(a,0)[0].options[0].includes('1.48'));const b=act('cbt-m7-energy-case');assert.ok(t.questions(b,0)[1].options[0].includes('81%'));assert.ok(t.questions(b,1)[1].options[0].includes('64%'));assert.ok(t.questions(b,2)[1].options[0].includes('90.25%'));});
test('Viewed later work never displaces the first open step',()=>{p.reset();p.visit(all[3].lessonId);assert.equal(t.next().lessonId,all[0].lessonId);finish(all[0]);assert.equal(t.next().lessonId,all[1].lessonId);});
test('All complete leads to no pending activity',()=>{all.forEach(finish);assert.equal(t.next(),null);});
test('Supported correct decisions are distinct from checks before feedback',()=>{const a=act('cbt-m7-transfer');finish(a);assert.equal(t.independent(a),true);const s=p.get(a.lessonId);s.decisions.q0.assisted=true;assert.equal(t.independent(a),false);});
test('Viewing creates no performance or completion',()=>{p.prepare('cbt-m1-test',2);p.visit('cbt-m1-test');assert.equal(p.get('cbt-m1-test').complete,false);assert.equal(p.get('cbt-m1-test').performed,false);});
test('Old schema 3 work is archived without certifying the revised task',()=>{const old=JSON.stringify({schema:3,activities:{'cbt-m2-groundeffect':{viewed:true,complete:true,reflection:'Old explanation',attempts:[{kind:'case-0',correct:true}]}},reviews:{m2:{reviewer:'Previous observer',note:'Previous note'}}});const x=load({getItem:k=>k==='helilab_training_v3'?old:null,setItem(){}});assert.equal(x.HLProgress.get('cbt-m2-groundeffect').complete,false);assert.equal(x.HLProgress.get('cbt-m2-groundeffect').prior.reflection,'Old explanation');assert.equal(x.HLProgress.all().reviews.m2.note,'Previous note');});
test('Backup preserves limitation, native checkpoint, attempt support and review criteria',()=>{p.patch('cbt-m1-test',{limitation:'Static model',checkpoint:{step:4,inputs:[{label:'pitch',value:'12'}]},revealed:['question-1']});p.attempt('cbt-m1-test','decision',true,'Retry',{assisted:true,variant:2,question:'question-1',choice:0});p.review('m1',{reviewer:'Observer',note:'Evidence in new case',criteria:{limits:'supported',mechanism:'independent'},version:2});const data=p.export();p.reset();p.import(data);assert.equal(p.get('cbt-m1-test').limitation,'Static model');assert.equal(p.get('cbt-m1-test').checkpoint.step,4);assert.equal(p.get('cbt-m1-test').attempts.at(-1).assisted,true);assert.equal(p.all().reviews.m1.criteria.limits,'supported');});
test('Structurally invalid imported snapshots cannot crash or satisfy a task',()=>{const x=load();const record={schema:4,activities:{'cbt-m1-bigpicture':{version:2,snapshots:[{values:{result:'1'}},{model:'wBigPicture',inputs:{},values:{x:1},selected:{},state:{},evidence:{}}]}},reviews:{}};x.HLProgress.import(JSON.stringify(record));assert.equal(x.HLProgress.get('cbt-m1-bigpicture').snapshots.length,0);assert.equal(x.HLTraining.complete(x.HLTraining.activities()[0]),false);});
test('Malformed imports leave the existing record intact',()=>{const before=p.export();for(const bad of ['null','[]','{','{"schema":2,"activities":{},"reviews":{}}'])assert.throws(()=>p.import(bad));assert.equal(p.export(),before);});
test('Blocked storage keeps a usable exportable session',()=>{const x=load({getItem(){throw Error('denied')},setItem(){throw Error('denied')}});x.HLProgress.visit('cbt-m1-test');assert.equal(x.HLProgress.persistent(),false);assert.equal(JSON.parse(x.HLProgress.export()).activities['cbt-m1-test'].viewed,true);});
test('Malformed stored state recovers without losing access to the curriculum',()=>{const x=load({getItem:()=>'{"schema":3,"activities":null}',setItem(){}});assert.equal(x.HLTraining.activities().length,29);assert.equal(x.HLProgress.get('cbt-m1-bigpicture').complete,false);});
test('Reset removes evidence and reviewer entries',()=>{p.reset();assert.equal(Object.keys(p.all().reviews).length,0);assert.equal(Object.keys(p.all().activities).length,0);});
const observed=act('cbt-m1-transfer'),module1=modules[0];
const observe=()=>p.review('m1',{reviewer:'Observer',note:'Changed conditions explained using the saved comparison',version:t.VERSION,criteria:{conditions:'independent',prediction:'supported',evidence:'independent',mechanism:'discuss'},...t.observationContext(observed)});
test('An observation identifies one current case and retains unobserved criteria',()=>{finish(observed);observe();const o=t.observation(module1);assert.equal(o.current,true);assert.equal(o.activity.lessonId,observed.lessonId);assert.equal(o.counts.independent,2);assert.equal(o.counts.unobserved,1);assert.equal(o.counts.supported,1);});
test('Navigation and unsaved model exploration do not invalidate an observation',()=>{p.visit(observed.lessonId);p.patch(observed.lessonId,{checkpoint:{inputs:[{label:'pitch',value:'12'}]}});assert.equal(t.observation(module1).current,true);});
test('Changed case, explanation, decisions and saved evidence invalidate a prior observation',()=>{for(const field of [{variant:1},{reflection:'A different conclusion'},{snapshots:[]},{decisions:{}}]){finish(observed);p.patch(observed.lessonId,{variant:0});observe();p.patch(observed.lessonId,field);assert.equal(t.observation(module1).current,false);assert.ok(p.all().reviews.m1.note);}});
test('Changed task version and question text cannot retain a current observation',()=>{finish(observed);p.patch(observed.lessonId,{variant:0});observe();const version=observed.version;observed.version++;assert.equal(t.observation(module1).current,false);observed.version=version;const checks=observed.checks;observed.checks=n=>checks(n).map(q=>({...q,prompt:q.prompt+' Revised.'}));assert.equal(t.observation(module1).current,false);observed.checks=checks;});
test('Older unbound observations remain available without a current verdict',()=>{p.review('m1',{reviewer:'Earlier observer',note:'Preserved earlier note',version:t.VERSION,criteria:{limits:'supported'}});assert.equal(t.observation(module1).current,false);assert.equal(p.all().reviews.m1.note,'Preserved earlier note');});
test('A new observation preserves earlier notes and ratings through backup',()=>{finish(observed);p.patch(observed.lessonId,{variant:0});observe();const backup=p.export();p.import(backup);assert.equal(t.observation(module1).current,true);assert.ok(p.all().reviews.m1.history.some(r=>r.note==='Preserved earlier note'&&r.criteria.limits==='supported'));assert.equal(p.all().reviews.m1.activityId,observed.lessonId);});
test('Backup key ordering does not falsely invalidate the observed work',()=>{const data=JSON.parse(p.export()),s=data.activities[observed.lessonId];s.decisions=Object.fromEntries(Object.entries(s.decisions).reverse());s.snapshots=s.snapshots.map(s=>({...s,inputs:Object.fromEntries(Object.entries(s.inputs).reverse())}));p.import(JSON.stringify(data));assert.equal(t.observation(module1).current,true);});
test('Review history is bounded and does not change activity completion',()=>{const before=t.complete(observed);for(let i=0;i<15;i++)observe();assert.equal(p.all().reviews.m1.history.length,12);assert.equal(t.complete(observed),before);});
console.log(`${count} learning checks passed`);
